language: ruby
script:   bundle exec rake
cache:    bundler
sudo:     false

before_install:
  - gem update --system
  - gem pristine bundler

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
  - jruby-9.1.16.0
  - jruby-head

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  exclude:
    - rvm: 2.3.7
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.16.0
    - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
