language: ruby
script:   bundle exec rake
cache:    bundler
sudo:     false

rvm:
  - 2.0.0
  - 2.1
  - 2.2.8
  - 2.3.5
  - 2.4.2
  - ruby-head
  - jruby-9.1.13.0
  - jruby-head

gemfile:
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_51.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_51.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.2.8
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.3.5
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.4.2
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.4.2
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.4.2
      gemfile: gemfiles/rails_41.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_32.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_40.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_41.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.13.0
    - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
    - gemfile: gemfiles/rails_32.gem
